### PR TITLE
Add Lorena Pantano affiliation and test image location

### PR DESCRIPTION
**Pull request by lpantano**
Hi,

I added my information and started adding an image to the organizing page.

I don't exactly where to put the image, is there ok? Let me know if I should follow other years templates or code where I can look at. I use `img` instead of markdown to let me control the size in the cases I need it.

Cheers

### CODE REVIEW

**Comment by lpantano** [comment]
As well, I have jekyll running on my computer so I can make some testing before PR.

**Comment by lwaldron** [comment]
Sorry for the slow review! How about using a table, like at http://bioc2019.bioconductor.org/code_of_conduct but with three columns (photo, name, affiliation)? Since these changes go live immediately on merging a pull request, perhaps I'll wait for you to make the table first.

**Comment by mtmorgan** [comment]
@lwaldron it's also possible to click the 'command line instructions' to the right of the 'Merge pull request' button and do things manually in two steps - pull the request to a local branch and merge, then push to github. These are cut-and-paste operations. Between the two steps the site can be previewed locally. This seems like a safer operating procedure in this case.

**Comment by lpantano** [comment]
@lwaldron, perfect, I'll do the changes today!

**Comment by lpantano** [comment]
@lwaldron, I added the table. I have two people I don't have their information or picture. As well, we have two types of photo sizes, I don't know if you want to normalize that. I could use HTML code or changes the picture size, although not a savvy in image processing.

Let me know

**Comment by lwaldron** [comment]
Thank you @lpantano , merged yesterday, your organizing committee page looks great.

**Comment by lwaldron** [comment]
> @lwaldron it's also possible to click the 'command line instructions' to the right of the 'Merge pull request' button and do things manually in two steps - pull the request to a local branch and merge, then push to github. These are cut-and-paste operations. Between the two steps the site can be previewed locally. This seems like a safer operating procedure in this case.

And @mtmorgan, thanks for the tip, I did it that way and it's handy.

**Pull request merged**
